### ISSUE TITLE
Unable to use after installation, error occurred

### ISSUE THREAD

**Issue by jasoncheng7115** [ThomasGsp/HyperProxmox#1]
Hello,

After the first execution：

`
root@hyperpve:/opt# runuser -l hyperproxmox -c '/usr/bin/python3.5 /opt/HyperProxmox/code/scripts/main/startup.py'
runuser: warning: cannot change directory to /home/hyperproxmox: No such file or directory
Traceback (most recent call last):
  File "/opt/HyperProxmox/code/scripts/main/startup.py", line 36, in <module>
    "logger": {"logs_level": localconf['logger']['logs_level'],
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'logger'
`

I've created /home/hyperproxmox and executed it the second time:

`
root@hyperpve:/opt#  /opt/HyperProxmox/code/scripts/main/startup.py
Traceback (most recent call last):
  File "/opt/HyperProxmox/code/scripts/main/startup.py", line 36, in <module>
    "logger": {"logs_level": localconf['logger']['logs_level'],
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'logger'
`

All config is consistent with setup step. Is there any other possibility?

thanks.

**Comment by ThomasGsp** [comment]
Hi,

Indeed, if you start outside the directory, you have this error.

Quick fix(recommended):
runuser -l hyperproxmox -c 'cd /opt/HyperProxmox/code/scripts/main && /usr/bin/python3.5 ./startup.py'

If you have tried to start without runuser, perhaps you will have permission issues.
It's really better to use runuser and not start in root.

Code fix branch master~dev:
I fixed this issue, but I did not test everything.
https://github.com/ThomasGsp/HyperProxmox/commit/cc19304db51e921c560f5ea00e6fc9be481e362e
https://github.com/ThomasGsp/HyperProxmox/commit/6214fb97540c5569b6ee04065c52525a93281738

Technically, you should use branch v1.0-beta.

Permissions Fix:
chown hyperproxmox: -R /opt/HyperProxmox
chmod 760 -R /opt/HyperProxmox
chown hyperproxmox: /var/log/hyperproxmox/

Thomas.

**Comment by jasoncheng7115** [comment]
Thank you,  @ThomasGsp 

I'm working now, but I have another problem:
Cluster was added using API post, but no cluster/node/vm information was found on webui.

![2018-12-18 11_35_15-hyperproxmox](https://user-images.githubusercontent.com/30381035/50130543-0e156800-02b9-11e9-800d-2129d292fd3d.png)

 I watched curl call API succeed (first time).

For the first time,
`
root@hyperpve:~# curl -H -XPOST -d '{
                        "name": "cluster2",
                        "url":"172.16.x.x",
                        "port": "8006",
                        "user": "root@pam",
                        "password": "password",
                        "template": "",
                        "storage_disk": "",
                        "exclude_nodes": [""],
                        "groups" : [""],
                        "weight": 1
                    }'  127.0.0.1:8080/api/v1/administration/cluster
{'value': 'clustecurl -H -XPOST -d '{ 'result': 'OK'}
`

The second time
`
root@hyperpve:~# curl -H -XPOST -d '{
                        "name": "cluster2",
                        "url":"172.16.x.x",
                        "port": "8006",
                        "user": "root@pam",
                        "password": "password",
                        "template": "",
                        "storage_disk": "",
                        "exclude_nodes": [""],
                        "groups" : [""],
                        "weight": 1
                    }'  127.0.0.1:8080/api/v1/administration/cluster
{'type': 'PROXMOX - VALUES', 'result': 'ERROR', 'value': 'Duplicate entry, please delete the current cluster or update it'}
`

HyperProxmox is a great project and I hope it grows stronger and stronger, thank you!

**Comment by ThomasGsp** [comment]
Cluster are not supported in hot-plug.
You have to stop and restart the service.

I found that runuser generate an issue to stop the service properly.
API will stay stuck on the port 8080.

```
root@xxxx:/opt/HyperProxmox #  netstat -lptn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      13659/python3.5     
```

Kill it: 
`ps aux|grep startup.py|tail -n +2|awk -F' ' '{print $2}'|xargs kill`

It's a bit dirty.

For the next start, switch to your hyperproxmox user to start it.
```
root@xxxx:/opt/HyperProxmox #  su - hyperproxmox 
No directory, logging in with HOME=/
$ cd /opt/HyperProxmox/code/scripts/main/
$ /usr/bin/python3.5 startup.py
This system need a passphrase to start:
Start API server...
http://127.0.0.1:8080/
...
```

It's not possible to use systemd to manage it (passphare startup check break the system).
Perhaps implement a PID management system or by call API.

Thanks you.
I will probably not implement new function, but just do the support / issue fix on the current code.

**Comment by jasoncheng7115** [comment]
Thank you. It's ready for use.

With API DELETE Cluster, it will succeed, but the VMs and NODEs information obtained will remain in HyperProxmox.

Thank you. It's ready for use.

With API DELETE Cluster, it will succeed, but the VM and NODE information obtained will remain in HyperProxmox.

I may contribute code to this project in the future.

**Comment by ThomasGsp** [comment]
Yes, but only on the selected date (top bar), when this cluster was available.
By default, the delay between two date is 300s. 
This delay can be short for production use. Change the value to 86400 (1day) can be a good solution.

https://github.com/ThomasGsp/HyperProxmox/blob/master/code/scripts/main/private/conf/config
```
[walker]
; Delay in seconds between to crawl (update)
walker: 300
```
